#!/bin/bash

set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
REPO_DIR=$(realpath ${SCRIPT_DIR}/..)

STENCIL_REPO=http://github.com/brown-csci1680/snowcast-template

main() {
    git remote rm stencil || true
    git remote add stencil $STENCIL_REPO

    git pull stencil main
}


main $@
